import Theme from "@bootstrapp/theme";
import { html } from "lit-html";
import $APP from "/app";

Theme.loadCSS("/node_modules/@bootstrapp/uix/theme.css", true);
Theme.loadTheme("gruvbox-dark");

$APP.routes.set({ "/showcase": () => html`<uix-showcase></uix-showcase>` });

$APP.addModule({
  name: "uix",
  path: "/node_modules/@bootstrapp",
  root: true,
  i18n: {
    pt: () => import("./locales/pt.js"),
  },
  themes: Theme.availableThemes,
  components: {
    navigation: [
      "accordion",
      "breadcrumbs",
      "menu",
      "navbar",
      "nav-item",
      "pagination",
      "sidebar",
      "tabs",
      "tree",
      "tree-item",
    ],
    overlay: [
      "alert-dialog",
      "drawer",
      "dropdown",
      "modal",
      "overlay",
      "popover",
      "tooltip",
      "popover-controller",
    ],
    display: [
      "avatar",
      "badge",
      "button",
      "calendar",
      "circle",
      "editable",
      "heading",
      "icon",
      "image",
      "link",
      "list",
      "list-item",
      "markdown",
      "media",
      "pattern",
      "stat",
      "table",
      "tag",
      "text",
    ],
    layout: [
      "card",
      "container",
      "data-table",
      "divider",
      "flex",
      "grid",
      "page",
      "panel",
      "section",
      "split-pane",
    ],
    app: ["app-container", "app-header", "bottom-nav", "title-bar"],
    page: [
      "cta-section",
      "faq-section",
      "feature-grid",
      "footer",
      "hero-section",
      "logo-cloud",
      "newsletter-section",
      "pricing-card",
      "pricing-table",
      "stats-section",
      "stat-card",
      "contact-avatar",
      "metric-hero-card",
      "testimonial-card",
      "testimonial-section",
    ],
    feedback: [
      "circular-progress",
      "progress-bar",
      "skeleton",
      "spinner",
      "toast",
    ],
    utility: [
      "device",
      "clipboard",
      "darkmode",
      "draggable",
      "droparea",
      "indexeddb-explorer",
      "seo",
      "theme-toggle",
    ],
    form: [
      "checkbox",
      "code",
      "file-upload",
      "form",
      "input",
      "form-input",
      "join",
      "number-input",
      "radio",
      "radio-group",
      "rating",
      "select",
      "slider",
      "switch",
      "textarea",
      "time",
    ],
    docs: [
      "showcase",
      "showcase-code-viewer",
      "showcase-property-editor",
      "showcase-sidebar",
      "theme-generator",
    ],
  },
});
